### ISSUE TITLE
Run callback in a new thread

### ISSUE THREAD

**Issue by yuyang0** [douban/pymesos#47]
In pymesos' current implementation, callback  blocks the `io_thread`, this is a big problem in some case.
such as

    def reregistered(self, driver, masterInfo):
        self.reconcile_all_running_tasks()
        with self.lock:
            self._connected = True

`reconcile_all_running_tasks` will wait util it received statusUpdate of these tasks, but because it blocks the `io_thread`, so the `statusUpdate` doesn't have a chance to run, finally it becomes a dead  loop.

**Comment by windreamer** [comment]
I think it is better to let user decide whether to run a particular callback synchronously or asynchronously.
If you decide to run it asynchronously, you can use thead, threadpool, coroutine or anything you like to run it. `pymesos` neither have the knowledge of the user's need, nor is able to force user to use any kind of these solution.

And assume, we are now callback in another thread, for example `_io_thread`. you would also be blocked infinitely, because `statusUpdate` cannot be called in `_io_thread` as it is occupied by `reconcile_all_running_tasks`.

If you aware that the old `pymesos` (<0.2.0) is using two threads instead of one, the main concern is we should not make IO lagged by slow callback. it is not for blocking issue. In this new version, we decide to simplify our design for better maintainability. and we see 20% performance boost in our production environment. I think it is worthy.

Hope my explanation is helpful.
thx

**Comment by yuyang0** [comment]
you are right, running all callback in a new thread can't solve this problem, but this is a trap for the user of this package. this package needs documentation. anyway thx

**Comment by windreamer** [comment]
yes, documentation is needed badly.
we will see whether we can spare some time to document this.
thank you for your support for this long time.
