### ISSUE TITLE
Scheduler failover flag is unsettable

### ISSUE THREAD

**Issue by efritz** [douban/pymesos#73]
There is no way to set the `_failover` flag in the scheduler driver. The current behavior means that if the scheduler throws an unexpected exception, all the tasks running on that framework are immediately terminated.

There should be a supported way to set this value to `True`.

**Comment by windreamer** [comment]
Thx. I will work on it.

**Comment by windreamer** [comment]
OK, this problem is a bit complicated.
`_failover` is a internal status to help `pymesos` decide whether or not to tear down the framework when process exits.
And user can make `_failover` `True` when using `sched.stop(failover=True)`

But I realize it is not enough to set `_failover` just when stop. When exceptions are raised, no `stop` would be called and the `_failover` will always `False`.

So I think we should add a default `failover` status when init the scheduler. And user can override the failover flag when stop.

**Comment by efritz** [comment]
This would be great - for now I've basically done this by setting the flag to true directly after initialization (but since it is setting a private car it is a temporary hack).

**Comment by windreamer** [comment]
fixed in #74

**Comment by efritz** [comment]
Any chance to cut a minor or patch version with this change?

**Comment by windreamer** [comment]
Of course! But I need to do some more test, and the new version I think will be available on Monday.

**Comment by efritz** [comment]
Any progress on a new version? Sorry to keep pestering.

**Comment by windreamer** [comment]
https://github.com/douban/pymesos/releases/tag/0.2.14 0.2.14 has been released 2 days ago

**Comment by windreamer** [comment]
But it seems pypi is not up to date

**Comment by efritz** [comment]
Sorry, didn't notice! Was waiting for the version in master to change.

**Comment by windreamer** [comment]
Damm, I forgot to bump the package version. My bad, 0.2.14 will be re-released shortly.

**Comment by efritz** [comment]
Thanks!

**Comment by windreamer** [comment]
0.2.14 re-released.
